# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_grpc_pb2 as test__grpc__pb2


class TestGrpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TestHello = channel.unary_unary(
        '/test_grpc.TestGrpc/TestHello',
        request_serializer=test__grpc__pb2.TestRequest.SerializeToString,
        response_deserializer=test__grpc__pb2.TestResponse.FromString,
        )
    self.Add = channel.unary_unary(
        '/test_grpc.TestGrpc/Add',
        request_serializer=test__grpc__pb2.AddRequest.SerializeToString,
        response_deserializer=test__grpc__pb2.AddResponse.FromString,
        )


class TestGrpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TestHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestGrpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TestHello': grpc.unary_unary_rpc_method_handler(
          servicer.TestHello,
          request_deserializer=test__grpc__pb2.TestRequest.FromString,
          response_serializer=test__grpc__pb2.TestResponse.SerializeToString,
      ),
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=test__grpc__pb2.AddRequest.FromString,
          response_serializer=test__grpc__pb2.AddResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test_grpc.TestGrpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
