version: '3'
services:
  nginx:
    container_name: nginx_flask
    image: nginx:latest
    # 端口映射
    ports:
      - 80:80
    # 磁盘映射
    volumes:
      - "$PWD/flasky/nginx/conf.d:/etc/nginx/conf.d"
      - "$PWD/flasky/www:/data/flasky/www"
    links:
      - flask:myflask
    networks:
      - flask_net
      
  flask:
    container_name: myflask
    build: .
    image: env_py36:1.1
    ports:
      - 8089:8089
    volumes:
      - "$PWD:/data/"
    # 环境变量
    environment:
      - MAIL_USERNAME=${ENV_MAIL_USERNAME}
      - MAIL_PASSWORD=${ENV_MAIL_PASSWORD}
      - FLASKY_ADMIN=${ENV_MAIL_ADMIN}
      - SECRET_KEY=${ENV_SECRET_KEY}
    networks:
      - flask_net
    
  mysql:
    container_name: flask_mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    # 环境变量
    environment:
      # mysql密码
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
    # 数据库数据持久化
    volumes:
      - "/Users/xliang/Documents/workspace/GitHub/docker/local_data/flask_mysql:/var/lib/mysql"
      - "$PWD/flasky/mysql.conf.d:/etc/mysql/mysql.conf.d"
    # command: [
    #   "--character-set-server=utf8mb4"
    # ]
    networks:
      flask_net:
        # 固定子网ip，网段必须再子网络172.10.*.*
        ipv4_address: 172.10.0.10
networks:
  # 配置docker network
  flask_net:
    driver: bridge
    ipam:
      config:
        # 子网络
        - subnet: 172.10.0.0/16